In [1]:
import sys
from pathlib import Path

PROJ_ROOT = "../../"
INPUT_FILE_PATH = PROJ_ROOT + "input"
sys.path.insert(0, PROJ_ROOT)

In [2]:
from src.preprocess.bathroom import pp_bathroom
from src.preprocess.read_file import read_file

In [5]:
df, _ = read_file(INPUT_FILE_PATH)

In [6]:
df["bathroom"].to_frame()

                                                bathroom
0       専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t浴室乾燥機\t／\t温水洗浄便座
1                                  専用トイレ／\tシャワー／\t温水洗浄便座
2      専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t浴室乾燥機\t／\t温水洗浄...
3         専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t温水洗浄便座／\t洗面台独立
4                   専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t追焚機能
...                                                  ...
31465       専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t追焚機能／\t洗面台独立
31466                                専用バス／\t専用トイレ／\tシャワー
31467                     バス・トイレ別／\tシャワー／\t追焚機能／\t温水洗浄便座
31468              専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t洗面台独立
31469                      専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー

[31470 rows x 1 columns]

In [7]:
pp_bathroom(df).loc[:, df.columns.str.startswith("ohe_bathroom")]

,ohe_bathroom_専用バス,ohe_bathroom_専用トイレ,ohe_bathroom_バス・トイレ別,ohe_bathroom_シャワー,ohe_bathroom_浴室乾燥機,ohe_bathroom_温水洗浄便座,ohe_bathroom_洗面台独立,ohe_bathroom_脱衣所,ohe_bathroom_追焚機能,ohe_bathroom_共同トイレ,ohe_bathroom_バスなし,ohe_bathroom_共同バス
0,1,1,1,1,1,1,0,0,0,0,0,0
1,0,1,0,1,0,1,0,0,0,0,0,0
2,1,1,1,1,1,1,1,1,0,0,0,0
3,1,1,1,1,0,1,1,0,0,0,0,0
4,1,1,1,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
31465,1,1,1,1,0,0,1,0,1,0,0,0
31466,1,1,0,1,0,0,0,0,0,0,0,0
31467,0,0,1,1,0,1,0,0,1,0,0,0
31468,1,1,1,1,0,0,1,0,0,0,0,0
31469,1,1,1,1,0,0,0,0,0,0,0,0