In [1]:
import sys
from pathlib import Path

PROJ_ROOT = "../../"
INPUT_FILE_PATH = PROJ_ROOT + "input"
sys.path.insert(0, PROJ_ROOT)

In [2]:
from src.preprocess.address import pp_address
from src.preprocess.read_file import read_file

In [3]:
train_df, test_df = read_file(INPUT_FILE_PATH)

In [4]:
import requests
import pandas as pd
import json


def get_code(address):
    response = requests.get("http://zipcoda.net/api", params={"address": address})
    response_dict = json.loads(response.text)
    zipcode = response_dict["items"][0]["zipcode"]
    return zipcode


def fe_postal(df, verbose=False):
    address = df["address"]
    postal_code = pd.Series([])
    for i, a in enumerate(address):
        if i % 100 == 0 and verbose:
            print(i)
            print(postal_code)
        postal_code = postal_code.append(pd.Series(get_code(a)), ignore_index=True)
#     df.loc[:, "postal_code"] = postal_code
    return postal_code

In [5]:
train_postal = fe_postal(train_df, verbose=True)

0
Series([], dtype: float64)
100
0     1140023
1     1040052
2     1510073
3     1660003
4     1250042
       ...
95    1640014
96    1310041
97    1018358
98    1360072
99    1670051
Length: 100, dtype: object
200
0      1140023
1      1040052
2      1510073
3      1660003
4      1250042
        ...
195    1770045
196    1570064
197    1650025
198    1160001
199    1660003
Length: 200, dtype: object
300
0      1140023
1      1040052
2      1510073
3      1660003
4      1250042
        ...
295    1640011
296    1408670
297    1530063
298    1710052
299    1330051
Length: 300, dtype: object
400
0      1140023
1      1040052
2      1510073
3      1660003
4      1250042
        ...
395    1300021
396    1440056
397    1730004
398    1300024
399    1300024
Length: 400, dtype: object
500
0      1140023
1      1040052
2      1510073
3      1660003
4      1250042
        ...
495    1750082
496    1330051
497    1460085
498    1320022
499    1710052
Length: 500, dtype: object
600
0      1140023
1      1040052
2      1510073
3      1660003
4      1250042
        ...
595    1300011
596    1330071
597    1740043
598    1790076
599    1420062
Length: 600, dtype: object
700
0      1140023
1      1040052
2      1510073
3      1660003
4      1250042
        ...
695    1520032
696    1730004
697    1110022
698    1060045
699    1620055
Length: 700, dtype: object
800
0      1140023
1      1040052
2      1510073
3      1660003
4      1250042
        ...
795    1560044
796    1240006
797    1130034
798    1110032
799    1640012
Length: 800, dtype: object
900
0      1140023
1      1040052
2      1510073
3      1660003
4      1250042
        ...
895    1550033
896    1440055
897    1420064
898    1680072
899    1698531
Length: 900, dtype: object
1000
0      1140023
1      1040052
2      1510073
3      1660003
4      1250042
        ...
995    1230873
996    1150043
997    1500021
998    1760002
999    1040051
Length: 1000, dtype: object
1100
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1095    1030002
1096    1210816
1097    1510072
1098    1140032
1099    1640013
Length: 1100, dtype: object
1200
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1195    1130033
1196    1730037
1197    1790085
1198    1420042
1199    1538654
Length: 1200, dtype: object
1300
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1295    1420064
1296    1418561
1297    1350046
1298    1730026
1299    1040053
Length: 1300, dtype: object
1400
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1395    1210814
1396    1710051
1397    1540002
1398    1140023
1399    1660003
Length: 1400, dtype: object
1500
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1495    1100005
1496    1230851
1497    1530041
1498    1240001
1499    1060031
Length: 1500, dtype: object
1600
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1595    1670032
1596    1710014
1597    1580081
1598    1240014
1599    1520002
Length: 1600, dtype: object
1700
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1695    1710014
1696    1110024
1697    1010032
1698    1040052
1699    1350022
Length: 1700, dtype: object
1800
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1795    1570061
1796    1250002
1797    1210012
1798    1560043
1799    1640011
Length: 1800, dtype: object
1900
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1895    1300026
1896    1080072
1897    1200006
1898    1550031
1899    1210056
Length: 1900, dtype: object
2000
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
1995    1530051
1996    1520035
1997    1050021
1998    1040061
1999    1320035
Length: 2000, dtype: object
2100
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2095    1680064
2096    1110054
2097    1440035
2098    1140000
2099    1570063
Length: 2100, dtype: object
2200
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2195    1010031
2196    1210051
2197    1690074
2198    1580081
2199    1200003
Length: 2200, dtype: object
2300
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2295    1460085
2296    1120012
2297    1230873
2298    1080075
2299    1240022
Length: 2300, dtype: object
2400
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2395    1510071
2396    1230872
2397    1700013
2398    1150055
2399    1500041
Length: 2400, dtype: object
2500
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2495    1400014
2496    1440035
2497    1140003
2498    1540004
2499    1570067
Length: 2500, dtype: object
2600
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2595    1760012
2596    1580082
2597    1550033
2598    1030015
2599    1750082
Length: 2600, dtype: object
2700
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2695    1340083
2696    1070052
2697    1300021
2698    1520004
2699    1570063
Length: 2700, dtype: object
2800
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2795    1770031
2796    1210813
2797    1358330
2798    1640012
2799    1118521
Length: 2800, dtype: object
2900
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2895    1710021
2896    1570061
2897    1210061
2898    1400002
2899    1618528
Length: 2900, dtype: object
3000
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
2995    1670051
2996    1500031
2997    1770041
2998    1640014
2999    1118511
Length: 3000, dtype: object
3100
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3095    1740076
3096    1440034
3097    1240005
3098    1790085
3099    1340081
Length: 3100, dtype: object
3200
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3195    1710031
3196    1330065
3197    1400013
3198    1500012
3199    1310041
Length: 3200, dtype: object
3300
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3295    1660001
3296    1040053
3297    1350016
3298    1230851
3299    1780063
Length: 3300, dtype: object
3400
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3395    1200035
3396    1080073
3397    1710031
3398    1740044
3399    1520002
Length: 3400, dtype: object
3500
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3495    1670054
3496    1300011
3497    1670021
3498    1668588
3499    1030002
Length: 3500, dtype: object
3600
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3595    1310041
3596    1620824
3597    1080072
3598    1710031
3599    1730004
Length: 3600, dtype: object
3700
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3695    1140000
3696    1710014
3697    1250033
3698    1120006
3699    1108708
Length: 3700, dtype: object
3800
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3795    1600023
3796    1230865
3797    1080075
3798    1510071
3799    1350045
Length: 3800, dtype: object
3900
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3895    1680071
3896    1460082
3897    1540004
3898    1680082
3899    1050013
Length: 3900, dtype: object
4000
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
3995    1530041
3996    1150055
3997    1310033
3998    1670051
3999    1640014
Length: 4000, dtype: object

4100
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4095    1580084
4096    1770045
4097    1760002
4098    1450066
4099    1770044
Length: 4100, dtype: object
4200
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4195    1110031
4196    1660013
4197    1160012
4198    1230851
4199    1410031
Length: 4200, dtype: object
4300
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4295    1350021
4296    1540024
4297    1240011
4298    1040052
4299    1520003
Length: 4300, dtype: object
4400
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4395    1050001
4396    1420051
4397    1560057
4398    1440054
4399    1540024
Length: 4400, dtype: object
4500
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4495    1670023
4496    1600017
4497    1650022
4498    1300025
4499    1730012
Length: 4500, dtype: object
4600
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4595    1040054
4596    1140002
4597    1770051
4598    1200043
4599    1058642
Length: 4600, dtype: object
4700
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4695    1710052
4696    1440033
4697    1320022
4698    1650022
4699    1340085
Length: 4700, dtype: object
4800
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4795    1430027
4796    1620041
4797    1730013
4798    1530051
4799    1570072
Length: 4800, dtype: object
4900
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4895    1650022
4896    1128516
4897    1160011
4898    1240013
4899    1360073
Length: 4900, dtype: object
5000
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
4995    1330056
4996    1080073
4997    1330054
4998    1450061
4999    1400002
Length: 5000, dtype: object
5100
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5095    1650032
5096    1580091
5097    1210816
5098    1430025
5099    1240024
Length: 5100, dtype: object
5200
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5195    1670052
5196    1100016
5197    1050012
5198    1030004
5199    1600011
Length: 5200, dtype: object
5300
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5295    1350043
5296    1330073
5297    1030008
5298    1030001
5299    1420063
Length: 5300, dtype: object
5400
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5395    1430027
5396    1460093
5397    1040051
5398    1640011
5399    1030007
Length: 5400, dtype: object
5500
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5495    1330051
5496    1230862
5497    1460094
5498    1510072
5499    1200003
Length: 5500, dtype: object
5600
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5595    1750084
5596    1330051
5597    1560053
5598    1080014
5599    1050001
Length: 5600, dtype: object
5700
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5695    1750092
5696    1520002
5697    1368880
5698    1340088
5699    1120014
Length: 5700, dtype: object
5800
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5795    1570065
5796    1730005
5797    1030002
5798    1358560
5799    1710014
Length: 5800, dtype: object
5900
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5895    1730037
5896    1040052
5897    1760005
5898    1710033
5899    1730027
Length: 5900, dtype: object
6000
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
5995    1358508
5996    1520031
5997    1510051
5998    1140023
5999    1210814
Length: 6000, dtype: object
6100
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6095    1150053
6096    1040061
6097    1308539
6098    1350091
6099    1660003
Length: 6100, dtype: object
6200
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6195    1408552
6196    1730037
6197    1520013
6198    1770035
6199    1140003
Length: 6200, dtype: object
6300
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6295    1400013
6296    1570076
6297    1710031
6298    1010021
6299    1580083
Length: 6300, dtype: object
6400
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6395    1068577
6396    1660003
6397    1140015
6398    1030025
6399    1710033
Length: 6400, dtype: object
6500
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6495    1300002
6496    1340081
6497    1520004
6498    1250042
6499    1460093
Length: 6500, dtype: object
6600
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6595    1100003
6596    1110032
6597    1640014
6598    1140034
6599    1540005
Length: 6600, dtype: object
6700
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6695    1300025
6696    1460082
6697    1530064
6698    1790074
6699    1650034
Length: 6700, dtype: object
6800
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6795    1640011
6796    1160014
6797    1740054
6798    1650031
6799    1080022
Length: 6800, dtype: object
6900
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6895    1680063
6896    1620067
6897    1790085
6898    1200035
6899    1600008
Length: 6900, dtype: object
7000
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
6995    1210012
6996    1330052
6997    1330073
6998    1300014
6999    1340088
Length: 7000, dtype: object
7100
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7095    1540011
7096    1130021
7097    1030002
7098    1510053
7099    1640011
Length: 7100, dtype: object
7200
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7195    1600022
7196    1780064
7197    1660012
7198    1130001
7199    1148588
Length: 7200, dtype: object
7300
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7295    1250063
7296    1600022
7297    1148510
7298    1620056
7299    1110052
Length: 7300, dtype: object
7400
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7395    1760021
7396    1300011
7397    1330052
7398    1580098
7399    1160012
Length: 7400, dtype: object
7500
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7495    1700001
7496    1570073
7497    1650034
7498    1660001
7499    1140015
Length: 7500, dtype: object
7600
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7595    1320011
7596    1660004
7597    1340003
7598    1358480
7599    1710042
Length: 7600, dtype: object
7700
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7695    1320031
7696    1690074
7697    1040041
7698    1520033
7699    1460082
Length: 7700, dtype: object
7800
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7795    1680063
7796    1050012
7797    1770034
7798    1110031
7799    1510064
Length: 7800, dtype: object
7900
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7895    1570065
7896    1670022
7897    1700004
7898    1140002
7899    1408616
Length: 7900, dtype: object
8000
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
7995    1530051
7996    1350016
7997    1680074
7998    1160001
7999    1580096
Length: 8000, dtype: object

8100
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8095    1408666
8096    1690075
8097    1300011
8098    1050003
8099    1030015
Length: 8100, dtype: object
8200
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8195    1580082
8196    1460084
8197    1730004
8198    1660001
8199    1770051
Length: 8200, dtype: object
8300
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8295    1440051
8296    1430016
8297    1700004
8298    1030007
8299    1340091
Length: 8300, dtype: object
8400
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8395    1130022
8396    1230852
8397    1780064
8398    1540022
8399    1140023
Length: 8400, dtype: object
8500
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8495    1400013
8496    1060031
8497    1040052
8498    1510072
8499    1040053
Length: 8500, dtype: object
8600
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8595    1580093
8596    1650034
8597    1350042
8598    1540016
8599    1230851
Length: 8600, dtype: object
8700
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8695    1110055
8696    1510071
8697    1700013
8698    1550032
8699    1340013
Length: 8700, dtype: object
8800
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8795    1420064
8796    1580095
8797    1350061
8798    1620851
8799    1580096
Length: 8800, dtype: object
8900
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8895    1408533
8896    1640011
8897    1410032
8898    1440052
8899    1530052
Length: 8900, dtype: object
9000
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
8995    1540002
8996    1240011
8997    1540024
8998    1430024
8999    1700011
Length: 9000, dtype: object
9100
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9095    1750094
9096    1310045
9097    1118531
9098    1300002
9099    1440035
Length: 9100, dtype: object
9200
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9195    1600022
9196    1770044
9197    1770034
9198    1510071
9199    1350023
Length: 9200, dtype: object
9300
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9295    1510063
9296    1030016
9297    1038212
9298    1160011
9299    1500041
Length: 9300, dtype: object
9400
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9395    1640012
9396    1210062
9397    1350062
9398    1350021
9399    1110041
Length: 9400, dtype: object
9500
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9495    1450064
9496    1340088
9497    1770033
9498    1330051
9499    1740053
Length: 9500, dtype: object
9600
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9595    1400013
9596    1570064
9597    1018519
9598    1120002
9599    1040054
Length: 9600, dtype: object
9700
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9695    1060032
9696    1088329
9697    1440034
9698    1640002
9699    1350043
Length: 9700, dtype: object
9800
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9795    1560043
9796    1768512
9797    1118521
9798    1150056
9799    1250054
Length: 9800, dtype: object
9900
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9895    1790073
9896    1140023
9897    1540012
9898    1340088
9899    1030008
Length: 9900, dtype: object
10000
0       1140023
1       1040052
2       1510073
3       1660003
4       1250042
         ...
9995    1420063
9996    1600023
9997    1510053
9998    1710051
9999    1560041
Length: 10000, dtype: object
10100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10095    1410021
10096    1048282
10097    1080014
10098    1580097
10099    1730004
Length: 10100, dtype: object
10200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10195    1240001
10196    1330073
10197    1540024
10198    1140032
10199    1440034
Length: 10200, dtype: object
10300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10295    1080022
10296    1300025
10297    1110055
10298    1710051
10299    1510072
Length: 10300, dtype: object
10400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10395    1040045
10396    1420041
10397    1700013
10398    1200015
10399    1420062
Length: 10400, dtype: object
10500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10495    1570072
10496    1150055
10497    1540023
10498    1240003
10499    1410022
Length: 10500, dtype: object
10600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10595    1768585
10596    1080071
10597    1650027
10598    1440042
10599    1560053
Length: 10600, dtype: object
10700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10695    1730032
10696    1200005
10697    1740053
10698    1420051
10699    1670054
Length: 10700, dtype: object
10800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10795    1730024
10796    1540012
10797    1580093
10798    1440046
10799    1680072
Length: 10800, dtype: object
10900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10895    1160003
10896    1010053
10897    1158711
10898    1650022
10899    1250053
Length: 10900, dtype: object
11000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
10995    1330061
10996    1040052
10997    1700013
10998    1430011
10999    1400002
Length: 11000, dtype: object
11100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11095    1340088
11096    1420062
11097    1350023
11098    1790082
11099    1660002
Length: 11100, dtype: object
11200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11195    1240012
11196    1680074
11197    1310033
11198    1210831
11199    1240022
Length: 11200, dtype: object
11300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11295    1350062
11296    1780064
11297    1710033
11298    1310033
11299    1520031
Length: 11300, dtype: object
11400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11395    1500011
11396    1560053
11397    1670042
11398    1148604
11399    1040054
Length: 11400, dtype: object
11500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11495    1410032
11496    1160014
11497    1700005
11498    1018419
11499    1230841
Length: 11500, dtype: object
11600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11595    1660003
11596    1540017
11597    1660011
11598    1660011
11599    1128558
Length: 11600, dtype: object
11700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11695    1430014
11696    1640001
11697    1540016
11698    1330051
11699    1160014
Length: 11700, dtype: object
11800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11795    1560055
11796    1320035
11797    1128531
11798    1408521
11799    1610032
Length: 11800, dtype: object
11900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11895    1350033
11896    1420051
11897    1350061
11898    1690075
11899    1080072
Length: 11900, dtype: object

12000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
11995    1128540
11996    1320022
11997    1520004
11998    1400011
11999    1730037
Length: 12000, dtype: object
12100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12095    1710052
12096    1030015
12097    1200005
12098    1400002
12099    1300021
Length: 12100, dtype: object
12200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12195    1560051
12196    1520011
12197    1680073
12198    1710032
12199    1460082
Length: 12200, dtype: object
12300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12295    1030002
12296    1438558
12297    1210816
12298    1690073
12299    1340083
Length: 12300, dtype: object
12400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12395    1510071
12396    1330061
12397    1660002
12398    1130022
12399    1440045
Length: 12400, dtype: object
12500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12495    1570067
12496    1210815
12497    1690075
12498    1200002
12499    1690075
Length: 12500, dtype: object
12600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12595    1320024
12596    1110032
12597    1710032
12598    1680072
12599    1580093
Length: 12600, dtype: object
12700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12695    1640003
12696    1700012
12697    1240023
12698    1048365
12699    1760023
Length: 12700, dtype: object
12800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12795    1420063
12796    1710031
12797    1540012
12798    1100012
12799    1068562
Length: 12800, dtype: object
12900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12895    1128540
12896    1500041
12897    1350011
12898    1048282
12899    1430012
Length: 12900, dtype: object
13000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
12995    1050023
12996    1650031
12997    1620812
12998    1350002
12999    1560054
Length: 13000, dtype: object
13100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13095    1430026
13096    1540016
13097    1058441
13098    1450072
13099    1110032
Length: 13100, dtype: object
13200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13195    1700002
13196    1430012
13197    1770033
13198    1620851
13199    1760002
Length: 13200, dtype: object
13300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13295    1210814
13296    1460082
13297    1360071
13298    1230865
13299    1230841
Length: 13300, dtype: object
13400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13395    1368580
13396    1600002
13397    1670052
13398    1520023
13399    1450061
Length: 13400, dtype: object
13500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13495    1620816
13496    1240014
13497    1240022
13498    1058414
13499    1300004
Length: 13500, dtype: object
13600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13595    1450064
13596    1150051
13597    1710051
13598    1230865
13599    1440052
Length: 13600, dtype: object
13700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13695    1640014
13696    1560057
13697    1300021
13698    1520004
13699    1640012
Length: 13700, dtype: object
13800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13795    1340091
13796    1500045
13797    1640003
13798    1150041
13799    1620812
Length: 13800, dtype: object
13900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13895    1618528
13896    1670032
13897    1430027
13898    1520022
13899    1330073
Length: 13900, dtype: object
14000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
13995    1680073
13996    1340088
13997    1420041
13998    1570062
13999    1580081
Length: 14000, dtype: object
14100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14095    1440051
14096    1350062
14097    1410031
14098    1500012
14099    1350012
Length: 14100, dtype: object
14200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14195    1500021
14196    1430027
14197    1710042
14198    1700013
14199    1600022
Length: 14200, dtype: object
14300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14295    1140014
14296    1588588
14297    1250002
14298    1450061
14299    1750092
Length: 14300, dtype: object
14400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14395    1518543
14396    1640011
14397    1680074
14398    1040045
14399    1500013
Length: 14400, dtype: object
14500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14495    1690073
14496    1640014
14497    1050004
14498    1540016
14499    1200015
Length: 14500, dtype: object
14600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14595    1350011
14596    1330054
14597    1330052
14598    1580097
14599    1400014
Length: 14600, dtype: object
14700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14695    1140014
14696    1560052
14697    1440051
14698    1400014
14699    1350033
Length: 14700, dtype: object
14800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14795    1010021
14796    1110032
14797    1620056
14798    1560054
14799    1510051
Length: 14800, dtype: object
14900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14895    1320035
14896    1610033
14897    1670051
14898    1530042
14899    1080073
Length: 14900, dtype: object
15000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
14995    1780064
14996    1110032
14997    1450071
14998    1160003
14999    1040052
Length: 15000, dtype: object
15100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15095    1550033
15096    1680073
15097    1160002
15098    1160012
15099    1640014
Length: 15100, dtype: object
15200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15195    1610032
15196    1740063
15197    1650021
15198    1358710
15199    1080014
Length: 15200, dtype: object
15300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15295    1300021
15296    1550031
15297    1760025
15298    1640013
15299    1030002
Length: 15300, dtype: object
15400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15395    1538512
15396    1520004
15397    1660004
15398    1570068
15399    1440056
Length: 15400, dtype: object
15500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15495    1110036
15496    1110025
15497    1160012
15498    1770042
15499    1340088
Length: 15500, dtype: object
15600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15595    1530063
15596    1740053
15597    1130021
15598    1110036
15599    1140002
Length: 15600, dtype: object

15700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15695    1640014
15696    1560042
15697    1770033
15698    1660003
15699    1310041
Length: 15700, dtype: object
15800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15795    1040054
15796    1140002
15797    1710014
15798    1210075
15799    1200005
Length: 15800, dtype: object
15900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15895    1730037
15896    1670052
15897    1640003
15898    1770041
15899    1570064
Length: 15900, dtype: object
16000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
15995    1040052
15996    1520002
15997    1460082
15998    1240012
15999    1230865
Length: 16000, dtype: object
16100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16095    1730026
16096    1330065
16097    1430023
16098    1400004
16099    1460092
Length: 16100, dtype: object
16200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16195    1300004
16196    1160002
16197    1120011
16198    1350042
16199    1050001
Length: 16200, dtype: object
16300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16295    1130021
16296    1400002
16297    1740076
16298    1790075
16299    1400015
Length: 16300, dtype: object
16400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16395    1548560
16396    1430025
16397    1210813
16398    1130022
16399    1350048
Length: 16400, dtype: object
16500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16495    1100012
16496    1200036
16497    1430012
16498    1250042
16499    1300005
Length: 16500, dtype: object
16600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16595    1570061
16596    1018559
16597    1200003
16598    1080074
16599    1730004
Length: 16600, dtype: object
16700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16695    1320031
16696    1140012
16697    1560055
16698    1040032
16699    1690073
Length: 16700, dtype: object
16800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16795    1788501
16796    1700013
16797    1520031
16798    1060044
16799    1118511
Length: 16800, dtype: object
16900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16895    1580096
16896    1700005
16897    1158711
16898    1640003
16899    1168584
Length: 16900, dtype: object
17000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
16995    1520035
16996    1660002
16997    1040052
16998    1500013
16999    1758571
Length: 17000, dtype: object
17100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17095    1080074
17096    1080074
17097    1110032
17098    1150055
17099    1058002
Length: 17100, dtype: object
17200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17195    1668535
17196    1660001
17197    1440056
17198    1680061
17199    1740063
Length: 17200, dtype: object
17300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17295    1450074
17296    1340085
17297    1430021
17298    1580084
17299    1710033
Length: 17300, dtype: object
17400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17395    1340085
17396    1620065
17397    1540012
17398    1070052
17399    1070052
Length: 17400, dtype: object
17500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17495    1620056
17496    1200044
17497    1130033
17498    1520034
17499    1020075
Length: 17500, dtype: object
17600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17595    1688555
17596    1540004
17597    1350016
17598    1330061
17599    1060046
Length: 17600, dtype: object
17700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17695    1050014
17696    1610034
17697    1680072
17698    1360076
17699    1120011
Length: 17700, dtype: object
17800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17795    1200031
17796    1700013
17797    1570074
17798    1150051
17799    1560043
Length: 17800, dtype: object
17900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17895    1430026
17896    1750092
17897    1360072
17898    1540004
17899    1430016
Length: 17900, dtype: object
18000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
17995    1230864
17996    1040045
17997    1538586
17998    1250002
17999    1400004
Length: 18000, dtype: object
18100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18095    1350048
18096    1230863
18097    1250041
18098    1330052
18099    1460082
Length: 18100, dtype: object
18200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18195    1210816
18196    1110032
18197    1040041
18198    1430016
18199    1740063
Length: 18200, dtype: object
18300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18295    1520002
18296    1340084
18297    1210073
18298    1758571
18299    1790074
Length: 18300, dtype: object
18400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18395    1500022
18396    1088329
18397    1200015
18398    1300004
18399    1030002
Length: 18400, dtype: object
18500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18495    1620816
18496    1770035
18497    1250032
18498    1330056
18499    1210836
Length: 18500, dtype: object
18600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18595    1058441
18596    1140016
18597    1520002
18598    1510066
18599    1530051
Length: 18600, dtype: object
18700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18695    1710051
18696    1520032
18697    1230873
18698    1330057
18699    1610033
Length: 18700, dtype: object
18800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18795    1210062
18796    1750093
18797    1450061
18798    1350011
18799    1130023
Length: 18800, dtype: object
18900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18895    1200015
18896    1660004
18897    1750091
18898    1048282
18899    1300014
Length: 18900, dtype: object
19000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
18995    1130022
18996    1310032
18997    1130033
18998    1230855
18999    1620812
Length: 19000, dtype: object
19100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19095    1120011
19096    1140031
19097    1660013
19098    1060044
19099    1200003
Length: 19100, dtype: object
19200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19195    1330002
19196    1740071
19197    1140000
19198    1130001
19199    1790073
Length: 19200, dtype: object
19300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19295    1110055
19296    1520013
19297    1460082
19298    1300025
19299    1130022
Length: 19300, dtype: object

19400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19395    1050012
19396    1110042
19397    1730001
19398    1788501
19399    1120005
Length: 19400, dtype: object
19500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19495    1710021
19496    1580097
19497    1348502
19498    1780064
19499    1510072
Length: 19500, dtype: object
19600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19595    1240014
19596    1038554
19597    1760002
19598    1340083
19599    1520034
Length: 19600, dtype: object
19700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19695    1730002
19696    1130034
19697    1710014
19698    1570077
19699    1550033
Length: 19700, dtype: object
19800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19795    1560043
19796    1320014
19797    1600015
19798    1680071
19799    1698531
Length: 19800, dtype: object
19900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19895    1540012
19896    1410031
19897    1210075
19898    1790081
19899    1650032
Length: 19900, dtype: object
20000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
19995    1660013
19996    1410022
19997    1560057
19998    1510064
19999    1048266
Length: 20000, dtype: object
20100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20095    1110055
20096    1500013
20097    1420054
20098    1350061
20099    1680063
Length: 20100, dtype: object
20200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20195    1340088
20196    1730004
20197    1760002
20198    1340085
20199    1120002
Length: 20200, dtype: object
20300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20295    1520031
20296    1140003
20297    1408640
20298    1358330
20299    1210012
Length: 20300, dtype: object
20400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20395    1410031
20396    1740055
20397    1330051
20398    1158711
20399    1790084
Length: 20400, dtype: object
20500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20495    1358480
20496    1780064
20497    1620853
20498    1730026
20499    1340015
Length: 20500, dtype: object
20600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20595    1730004
20596    1620811
20597    1540004
20598    1540015
20599    1060031
Length: 20600, dtype: object
20700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20695    1670054
20696    1530064
20697    1200003
20698    1680074
20699    1540022
Length: 20700, dtype: object
20800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20795    1250041
20796    1360072
20797    1760001
20798    1350011
20799    1160001
Length: 20800, dtype: object
20900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20895    1540002
20896    1560054
20897    1350016
20898    1570064
20899    1200042
Length: 20900, dtype: object
21000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
20995    1410021
20996    1040052
20997    1570066
20998    1740051
20999    1300005
Length: 21000, dtype: object
21100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21095    1300024
21096    1770051
21097    1538923
21098    1340083
21099    1538923
Length: 21100, dtype: object
21200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21195    1708440
21196    1670051
21197    1520035
21198    1120006
21199    1790071
Length: 21200, dtype: object
21300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21295    1320033
21296    1210816
21297    1350016
21298    1340084
21299    1450062
Length: 21300, dtype: object
21400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21395    1330052
21396    1640013
21397    1100016
21398    1200015
21399    1110041
Length: 21400, dtype: object
21500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21495    1510053
21496    1350015
21497    1330065
21498    1440051
21499    1310033
Length: 21500, dtype: object
21600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21595    1610032
21596    1110041
21597    1750092
21598    1680062
21599    1400013
Length: 21600, dtype: object
21700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21695    1410001
21696    1110032
21697    1330061
21698    1708450
21699    1460085
Length: 21700, dtype: object
21800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21795    1730004
21796    1500001
21797    1500011
21798    1300001
21799    1330065
Length: 21800, dtype: object
21900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21895    1760003
21896    1438558
21897    1060044
21898    1040052
21899    1340091
Length: 21900, dtype: object
22000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
21995    1400011
21996    1680074
21997    1060047
21998    1300015
21999    1670042
Length: 22000, dtype: object
22100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22095    1130034
22096    1680074
22097    1120012
22098    1110032
22099    1610031
Length: 22100, dtype: object
22200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22195    1640012
22196    1088532
22197    1700013
22198    1150052
22199    1340085
Length: 22200, dtype: object
22300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22295    1750082
22296    1160003
22297    1130022
22298    1200006
22299    1420043
Length: 22300, dtype: object
22400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22395    1570073
22396    1070052
22397    1460082
22398    1340081
22399    1770033
Length: 22400, dtype: object
22500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22495    1400011
22496    1330002
22497    1350023
22498    1030007
22499    1150051
Length: 22500, dtype: object
22600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22595    1580097
22596    1420063
22597    1350016
22598    1068655
22599    1030008
Length: 22600, dtype: object
22700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22695    1770052
22696    1430026
22697    1690075
22698    1750082
22699    1350052
Length: 22700, dtype: object
22800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22795    1570067
22796    1640001
22797    1450064
22798    1750084
22799    1350048
Length: 22800, dtype: object
22900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22895    1680065
22896    1110033
22897    1560043
22898    1030007
22899    1550031
Length: 22900, dtype: object
23000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
22995    1360072
22996    1440051
22997    1250002
22998    1640003
22999    1030007
Length: 23000, dtype: object

23100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23095    1050012
23096    1770045
23097    1368533
23098    1140014
23099    1038388
Length: 23100, dtype: object
23200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23195    1110053
23196    1230843
23197    1560053
23198    1250054
23199    1140023
Length: 23200, dtype: object
23300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23295    1580082
23296    1240011
23297    1730003
23298    1250052
23299    1200036
Length: 23300, dtype: object
23400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23395    1660001
23396    1300024
23397    1400013
23398    1350022
23399    1060031
Length: 23400, dtype: object
23500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23495    1040061
23496    1560057
23497    1680081
23498    1330044
23499    1060032
Length: 23500, dtype: object
23600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23595    1158555
23596    1640012
23597    1310032
23598    1400004
23599    1240004
Length: 23600, dtype: object
23700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23695    1520013
23696    1330073
23697    1730037
23698    1710014
23699    1700002
Length: 23700, dtype: object
23800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23795    1690074
23796    1530065
23797    1070051
23798    1538654
23799    1350062
Length: 23800, dtype: object
23900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23895    1580087
23896    1160003
23897    1520012
23898    1770035
23899    1200041
Length: 23900, dtype: object
24000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
23995    1640003
23996    1780064
23997    1130021
23998    1538586
23999    1540001
Length: 24000, dtype: object
24100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24095    1110032
24096    1660001
24097    1300002
24098    1160011
24099    1570062
Length: 24100, dtype: object
24200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24195    1040061
24196    1230851
24197    1200003
24198    1780065
24199    1400004
Length: 24200, dtype: object
24300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24295    1040051
24296    1440052
24297    1650024
24298    1340085
24299    1670054
Length: 24300, dtype: object
24400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24395    1690051
24396    1120002
24397    1110031
24398    1660013
24399    1580093
Length: 24400, dtype: object
24500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24495    1080071
24496    1130033
24497    1160002
24498    1330051
24499    1770031
Length: 24500, dtype: object
24600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24595    1660003
24596    1640013
24597    1750094
24598    1530061
24599    1070052
Length: 24600, dtype: object
24700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24695    1440034
24696    1710052
24697    1250053
24698    1200015
24699    1320031
Length: 24700, dtype: object
24800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24795    1660004
24796    1350042
24797    1350042
24798    1160014
24799    1328533
Length: 24800, dtype: object
24900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24895    1640013
24896    1080023
24897    1660004
24898    1670021
24899    1730027
Length: 24900, dtype: object
25000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
24995    1058432
24996    1430016
24997    1530042
24998    1348502
24999    1540011
Length: 25000, dtype: object
25100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25095    1400014
25096    1770045
25097    1360076
25098    1680073
25099    1650035
Length: 25100, dtype: object
25200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25195    1640002
25196    1350041
25197    1038554
25198    1670035
25199    1040033
Length: 25200, dtype: object
25300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25295    1710052
25296    1520003
25297    1560045
25298    1770045
25299    1200003
Length: 25300, dtype: object
25400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25395    1568504
25396    1560043
25397    1540002
25398    1340083
25399    1500011
Length: 25400, dtype: object
25500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25495    1560057
25496    1150055
25497    1620814
25498    1710051
25499    1040033
Length: 25500, dtype: object
25600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25595    1350048
25596    1340081
25597    1250052
25598    1420053
25599    1360073
Length: 25600, dtype: object
25700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25695    1770045
25696    1250041
25697    1520012
25698    1300022
25699    1680071
Length: 25700, dtype: object
25800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25795    1430024
25796    1710033
25797    1350004
25798    1140001
25799    1250061
Length: 25800, dtype: object
25900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25895    1740055
25896    1230865
25897    1250061
25898    1340084
25899    1750045
Length: 25900, dtype: object
26000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
25995    1580094
25996    1650022
25997    1430016
25998    1250042
25999    1210831
Length: 26000, dtype: object
26100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26095    1510063
26096    1210801
26097    1300021
26098    1200014
26099    1060047
Length: 26100, dtype: object
26200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26195    1060044
26196    1520031
26197    1460093
26198    1340084
26199    1730031
Length: 26200, dtype: object
26300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26295    1730021
26296    1040041
26297    1610033
26298    1350004
26299    1540012
Length: 26300, dtype: object
26400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26395    1210816
26396    1730005
26397    1750094
26398    1430026
26399    1430026
Length: 26400, dtype: object
26500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26495    1350011
26496    1130001
26497    1240024
26498    1510071
26499    1250031
Length: 26500, dtype: object
26600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26595    1540004
26596    1340091
26597    1238514
26598    1430015
26599    1430013
Length: 26600, dtype: object
26700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26695    1650031
26696    1358480
26697    1700004
26698    1350063
26699    1420064
Length: 26700, dtype: object

26800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26795    1230865
26796    1700005
26797    1640001
26798    1300024
26799    1600022
Length: 26800, dtype: object
26900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26895    1200034
26896    1010043
26897    1210073
26898    1308520
26899    1790076
Length: 26900, dtype: object
27000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
26995    1690074
26996    1640012
26997    1350048
26998    1230872
26999    1420064
Length: 27000, dtype: object
27100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27095    1160003
27096    1200014
27097    1160002
27098    1700004
27099    1350033
Length: 27100, dtype: object
27200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27195    1200025
27196    1320035
27197    1740046
27198    1040053
27199    1520011
Length: 27200, dtype: object
27300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27295    1760002
27296    1350046
27297    1350043
27298    1340091
27299    1320031
Length: 27300, dtype: object
27400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27395    1650027
27396    1540002
27397    1100012
27398    1060045
27399    1760012
Length: 27400, dtype: object
27500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27495    1130033
27496    1080071
27497    1620053
27498    1080014
27499    1310043
Length: 27500, dtype: object
27600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27595    1410021
27596    1780064
27597    1240001
27598    1040054
27599    1770041
Length: 27600, dtype: object
27700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27695    1500013
27696    1408552
27697    1250051
27698    1330073
27699    1110032
Length: 27700, dtype: object
27800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27795    1438558
27796    1520002
27797    1680082
27798    1660011
27799    1730025
Length: 27800, dtype: object
27900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27895    1730004
27896    1130031
27897    1100004
27898    1300025
27899    1750092
Length: 27900, dtype: object
28000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
27995    1760002
27996    1680072
27997    1368620
27998    1650024
27999    1160011
Length: 28000, dtype: object
28100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28095    1148555
28096    1230865
28097    1330056
28098    1640002
28099    1500012
Length: 28100, dtype: object
28200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28195    1660015
28196    1360074
28197    1650034
28198    1440055
28199    1230862
Length: 28200, dtype: object
28300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28295    1120002
28296    1030015
28297    1160002
28298    1430024
28299    1680064
Length: 28300, dtype: object
28400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28395    1550031
28396    1350011
28397    1538586
28398    1340003
28399    1540012
Length: 28400, dtype: object
28500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28495    1120014
28496    1100003
28497    1560043
28498    1538923
28499    1550033
Length: 28500, dtype: object
28600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28595    1560055
28596    1730004
28597    1530043
28598    1510071
28599    1640012
Length: 28600, dtype: object
28700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28695    1740061
28696    1460094
28697    1230864
28698    1631071
28699    1300011
Length: 28700, dtype: object
28800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28795    1230851
28796    1750045
28797    1710021
28798    1160011
28799    1320011
Length: 28800, dtype: object
28900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28895    1080073
28896    1160003
28897    1430024
28898    1138601
28899    1450063
Length: 28900, dtype: object
29000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
28995    1670053
28996    1330051
28997    1680073
28998    1530061
28999    1680064
Length: 29000, dtype: object
29100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29095    1430025
29096    1120014
29097    1350062
29098    1438507
29099    1330053
Length: 29100, dtype: object
29200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29195    1730014
29196    1030011
29197    1520012
29198    1200005
29199    1018544
Length: 29200, dtype: object
29300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29295    1438507
29296    1340085
29297    1350042
29298    1350063
29299    1360076
Length: 29300, dtype: object
29400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29395    1690075
29396    1570067
29397    1760012
29398    1570072
29399    1570062
Length: 29400, dtype: object
29500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29495    1300011
29496    1610032
29497    1680063
29498    1350033
29499    1080075
Length: 29500, dtype: object
29600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29595    1510064
29596    1010064
29597    1730011
29598    1600023
29599    1780062
Length: 29600, dtype: object
29700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29695    1420064
29696    1500045
29697    1030013
29698    1750083
29699    1080014
Length: 29700, dtype: object
29800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29795    1430012
29796    1790076
29797    1010047
29798    1520023
29799    1160001
Length: 29800, dtype: object
29900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29895    1300022
29896    1248538
29897    1560054
29898    1730004
29899    1760004
Length: 29900, dtype: object
30000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
29995    1750094
29996    1040052
29997    1240022
29998    1110031
29999    1680063
Length: 30000, dtype: object
30100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30095    1330065
30096    1520011
30097    1250042
30098    1230872
30099    1300024
Length: 30100, dtype: object
30200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30195    1040043
30196    1730001
30197    1070062
30198    1330056
30199    1650022
Length: 30200, dtype: object
30300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30295    1740056
30296    1230851
30297    1700012
30298    1060032
30299    1080074
Length: 30300, dtype: object
30400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30395    1450066
30396    1150053
30397    1250053
30398    1150056
30399    1160001
Length: 30400, dtype: object

30500
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30495    1670021
30496    1110032
30497    1240006
30498    1410021
30499    1360073
Length: 30500, dtype: object
30600
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30595    1130022
30596    1300023
30597    1500013
30598    1130001
30599    1110041
Length: 30600, dtype: object
30700
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30695    1770053
30696    1650027
30697    1040052
30698    1530063
30699    1300004
Length: 30700, dtype: object
30800
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30795    1450073
30796    1730004
30797    1350061
30798    1760012
30799    1420062
Length: 30800, dtype: object
30900
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30895    1360071
30896    1570072
30897    1450064
30898    1760006
30899    1040061
Length: 30900, dtype: object
31000
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
30995    1250032
30996    1660001
30997    1110032
30998    1360072
30999    1430023
Length: 31000, dtype: object
31100
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
31095    1790082
31096    1730014
31097    1440055
31098    1100014
31099    1100008
Length: 31100, dtype: object
31200
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
31195    1210011
31196    1418507
31197    1200005
31198    1520031
31199    1780062
Length: 31200, dtype: object
31300
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
31295    1210064
31296    1230851
31297    1440031
31298    1230852
31299    1050022
Length: 31300, dtype: object
31400
0        1140023
1        1040052
2        1510073
3        1660003
4        1250042
          ...
31395    1060032
31396    1300013
31397    1540004
31398    1660003
31399    1530051
Length: 31400, dtype: object

In [ ]:
test_postal = fe_postal(test_df, verbose=True)

0
Series([], dtype: float64)
100
0     1580081
1     1520023
2     1700011
3     1680063
4     1660013
       ...
95    1040043
96    1550031
97    1140012
98    1740056
99    1790071
Length: 100, dtype: object
200
0      1580081
1      1520023
2      1700011
3      1680063
4      1660013
        ...
195    1160013
196    1570062
197    1330073
198    1080073
199    1620054
Length: 200, dtype: object
300
0      1580081
1      1520023
2      1700011
3      1680063
4      1660013
        ...
295    1140024
296    1570065
297    1330061
298    1330002
299    1040033
Length: 300, dtype: object
400
0      1580081
1      1520023
2      1700011
3      1680063
4      1660013
        ...
395    1580098
396    1570062
397    1440051
398    1530042
399    1150051
Length: 400, dtype: object
500
0      1580081
1      1520023
2      1700011
3      1680063
4      1660013
        ...
495    1700005
496    1040054
497    1128540
498    1650031
499    1540004
Length: 500, dtype: object
600
0      1580081
1      1520023
2      1700011
3      1680063
4      1660013
        ...
595    1410021
596    1600022
597    1740056
598    1240023
599    1350007
Length: 600, dtype: object
700
0      1580081
1      1520023
2      1700011
3      1680063
4      1660013
        ...
695    1340081
696    1230863
697    1230862
698    1080075
699    1640012
Length: 700, dtype: object
800
0      1580081
1      1520023
2      1700011
3      1680063
4      1660013
        ...
795    1508940
796    1440051
797    1740052
798    1330057
799    1120011
Length: 800, dtype: object
900
0      1580081
1      1520023
2      1700011
3      1680063
4      1660013
        ...
895    1430016
896    1640012
897    1250062
898    1240012
899    1570061
Length: 900, dtype: object
1000
0      1580081
1      1520023
2      1700011
3      1680063
4      1660013
        ...
995    1110022
996    1510071
997    1160002
998    1140024
999    1660001
Length: 1000, dtype: object
1100
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1095    1600004
1096    1760001
1097    1020072
1098    1420064
1099    1550031
Length: 1100, dtype: object
1200
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1195    1140004
1196    1540004
1197    1150051
1198    1030002
1199    1710022
Length: 1200, dtype: object
1300
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1295    1700002
1296    1030007
1297    1040053
1298    1628670
1299    1640011
Length: 1300, dtype: object
1400
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1395    1650033
1396    1730037
1397    1750091
1398    1570073
1399    1058446
Length: 1400, dtype: object
1500
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1495    1030023
1496    1040045
1497    1430015
1498    1460093
1499    1080072
Length: 1500, dtype: object
1600
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1595    1350042
1596    1030002
1597    1570073
1598    1250062
1599    1320025
Length: 1600, dtype: object
1700
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1695    1350001
1696    1680074
1697    1510072
1698    1030026
1699    1040045
Length: 1700, dtype: object
1800
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1795    1320031
1796    1030026
1797    1660013
1798    1210836
1799    1780063
Length: 1800, dtype: object
1900
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1895    1108507
1896    1240011
1897    1048584
1898    1360071
1899    1130022
Length: 1900, dtype: object
2000
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
1995    1310045
1996    1660003
1997    1140021
1998    1250061
1999    1440056
Length: 2000, dtype: object
2100
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2095    1660002
2096    1250032
2097    1080022
2098    1430014
2099    1330056
Length: 2100, dtype: object
2200
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2195    1030007
2196    1040043
2197    1200001
2198    1340091
2199    1310034
Length: 2200, dtype: object
2300
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2295    1330051
2296    1030015
2297    1300021
2298    1350091
2299    1450062
Length: 2300, dtype: object
2400
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2395    1570062
2396    1200015
2397    1670053
2398    1600007
2399    1540004
Length: 2400, dtype: object
2500
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2495    1110021
2496    1540002
2497    1350043
2498    1348502
2499    1210075
Length: 2500, dtype: object
2600
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2595    1510071
2596    1110031
2597    1200014
2598    1580093
2599    1120002
Length: 2600, dtype: object
2700
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2695    1610034
2696    1050022
2697    1100001
2698    1160014
2699    1240012
Length: 2700, dtype: object
2800
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2795    1560044
2796    1660003
2797    1230842
2798    1130033
2799    1458515
Length: 2800, dtype: object
2900
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2895    1660012
2896    1330054
2897    1110041
2898    1358560
2899    1210831
Length: 2900, dtype: object
3000
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
2995    1540011
2996    1510072
2997    1400013
2998    1510072
2999    1080074
Length: 3000, dtype: object
3100
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3095    1520022
3096    1690074
3097    1210831
3098    1670052
3099    1620814
Length: 3100, dtype: object
3200
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3195    1350032
3196    1750082
3197    1568504
3198    1330051
3199    1670053
Length: 3200, dtype: object
3300
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3295    1250061
3296    1230863
3297    1110032
3298    1640002
3299    1690074
Length: 3300, dtype: object
3400
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3395    1650032
3396    1320031
3397    1320021
3398    1330073
3399    1520002
Length: 3400, dtype: object
3500
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3495    1730024
3496    1650027
3497    1230843
3498    1640012
3499    1020082
Length: 3500, dtype: object
3600
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3595    1570062
3596    1200005
3597    1640012
3598    1110032
3599    1360071
Length: 3600, dtype: object
3700
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3695    1230851
3696    1440056
3697    1340003
3698    1790085
3699    1400015
Length: 3700, dtype: object
3800
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3795    1640012
3796    1710033
3797    1650024
3798    1430025
3799    1460092
Length: 3800, dtype: object
3900
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3895    1020092
3896    1320031
3897    1420054
3898    1300004
3899    1200015
Length: 3900, dtype: object
4000
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
3995    1360071
3996    1330065
3997    1080072
3998    1580081
3999    1420042
Length: 4000, dtype: object

4100
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4095    1038251
4096    1580083
4097    1360073
4098    1710051
4099    1780065
Length: 4100, dtype: object
4200
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4195    1760012
4196    1030007
4197    1120011
4198    1250053
4199    1150043
Length: 4200, dtype: object
4300
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4295    1040054
4296    1350061
4297    1510064
4298    1240024
4299    1018425
Length: 4300, dtype: object
4400
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4395    1140004
4396    1610034
4397    1030004
4398    1160003
4399    1310045
Length: 4400, dtype: object
4500
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4495    1040041
4496    1660002
4497    1520031
4498    1650034
4499    1430015
Length: 4500, dtype: object
4600
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4595    1430027
4596    1350004
4597    1230873
4598    1068569
4599    1440052
Length: 4600, dtype: object
4700
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4695    1150042
4696    1360074
4697    1640011
4698    1788501
4699    1200014
Length: 4700, dtype: object
4800
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4795    1660001
4796    1240014
4797    1430016
4798    1770042
4799    1770034
Length: 4800, dtype: object
4900
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4895    1330073
4896    1310041
4897    1700013
4898    1310043
4899    1400015
Length: 4900, dtype: object
5000
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
4995    1200033
4996    1150043
4997    1110032
4998    1730002
4999    1350006
Length: 5000, dtype: object
5100
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5095    1700003
5096    1350016
5097    1690075
5098    1200002
5099    1350042
Length: 5100, dtype: object
5200
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5195    1210813
5196    1670051
5197    1420041
5198    1210812
5199    1300001
Length: 5200, dtype: object
5300
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5295    1340085
5296    1560057
5297    1740076
5298    1410031
5299    1350061
Length: 5300, dtype: object
5400
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5395    1770041
5396    1210073
5397    1040033
5398    1760001
5399    1700005
Length: 5400, dtype: object
5500
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5495    1320035
5496    1680081
5497    1710014
5498    1010046
5499    1358330
Length: 5500, dtype: object
5600
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5595    1730013
5596    1320011
5597    1420043
5598    1240014
5599    1118639
Length: 5600, dtype: object
5700
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5695    1730004
5696    1118521
5697    1360071
5698    1080075
5699    1010021
Length: 5700, dtype: object
5800
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5795    1250041
5796    1140022
5797    1790081
5798    1070062
5799    1760021
Length: 5800, dtype: object
5900
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5895    1570062
5896    1760014
5897    1320033
5898    1110032
5899    1150053
Length: 5900, dtype: object
6000
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
5995    1580092
5996    1200022
5997    1350033
5998    1200015
5999    1560052
Length: 6000, dtype: object
6100
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
6095    1250041
6096    1550033
6097    1308588
6098    1140011
6099    1320031
Length: 6100, dtype: object
6200
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
6195    1010031
6196    1790073
6197    1500012
6198    1610033
6199    1760012
Length: 6200, dtype: object
6300
0       1580081
1       1520023
2       1700011
3       1680063
4       1660013
         ...
6295    1040051
6296    1068577
6297    1780063
6298    1670052
6299    1160001
Length: 6300, dtype: object